FROM ansible/ansible-runner

RUN pip install --upgrade pip==20.0.2
RUN pip install --upgrade setuptools==44.1.0
RUN pip install --ignore-installed openshift
RUN pip install hvac jmespath
RUN pip install --upgrade ansible==2.9.7
